Proposal to add Auditzy to Github Integration List
GoogleChrome/lighthouse pull request #13976
Opened 2022-05-09 16:06 UTC by lowkeyAngry

**Summary**
Change in the readme.md file regarding listing Auditzy in the Google Lighthouse Integration List

2022-06-07 06:42 UTC, lowkeyAngry commented
Hey, Lighthouse Team,

We as in the Auditzy™ Team are patiently waiting to see our name on the list of the tools that use lighthouse and have built something on top of it. Please if guys could review this PR and merge it, it will be great.

Thanks in advance!

2022-06-15 22:37 UTC, adamraine requested changes

2022-06-15 22:37 UTC, adamraine commented on readme.md
> +* **[Auditzy](https://auditzy.com)** - Auditzy™ is a robust website auditing & monitoring tool which lets you analyze your web page(s) pre-user journey. Analyze the Competitor Health Metric, Core-Web
```suggestion
* **[Auditzy](https://auditzy.com)** - Auditzy™ is a robust website auditing & monitoring tool which lets you analyze your web page(s) pre-user journey. Analyze the Competitor Health Metric, Core Web Vitals, and Technology. Compare your web pages with your competitors to understand where you are leading or lagging. Real-time notification with Slack. Have Seamless Collaboration with Multiple Teams. Automate your Audits hourly, daily, weekly, and so on. It has a free trial with pay as you go plans.
```

2022-06-22 22:01 UTC, adamraine approved these changes

2022-08-24 21:08 UTC, paulirish approved these changes

2022-08-24 22:28 UTC, merged