deps: downgrade dev puppeteer
GoogleChrome/lighthouse pull request #14280
Opened 2022-08-10 23:19 UTC by adamraine

Puppeteer 16 started pausing and resuming targets which shouldn't affect normal Lighthouse execution, but it will be a problem if we want to attach to worker targets https://github.com/GoogleChrome/lighthouse/issues/14211.

Our DT smokes attach to the LH worker to inject the config, and Puppeteer was resuming the the worker target before we inject the config.

This downgrade should only affect our DT smoke runner script and not anything actually shipped with Lighthouse.

2022-08-10 23:29 UTC, brendankenny commented
What're you thinking long term for this?

2022-08-10 23:33 UTC, adamraine commented
> What're you thinking long term for this?

I'm gonna file an issue upstream and talk to @caseq again. Ideally clients don't need to coordinate when attaching to worker targets.

I tried various Puppeteer modifications with the new target interceptor stuff but haven't get anything working yet.

2022-08-11 16:54 UTC, adamraine commented
https://bugs.chromium.org/p/chromium/issues/detail?id=1352175

2022-08-11 19:14 UTC, paulirish requested changes
> Our DT smokes attach to the LH worker to inject the config, and Puppeteer was resuming the the worker target before we inject the config.

This config injection is a ridiculous hack. If we need to escalate something to CDP folks or puppeteer folks, I certainly don't want the basis of it to be preserving our hacky technique.

▶️  https://github.com/GoogleChrome/lighthouse/pull/14205#discussion_r919409794

2022-08-11 20:01 UTC, adamraine commented
> This config injection is a ridiculous hack. If we need to escalate something to CDP folks or puppeteer folks, I certainly don't want the basis of it to be preserving our hacky technique.

It's not the only basis. There are other good reasons Lighthouse would want to attach to worker targets without interference namely https://github.com/GoogleChrome/lighthouse/issues/14211.

2022-08-11 20:16 UTC, adamraine commented
Discussed offline, we are going to refactor our DT frontend code so we don't need this worker hack. Idea is that we will send a full `config` to the worker instead of just the `flags`.

2022-08-11 21:44 UTC, closed without merging