report: avoid really slow regexes for long urls
GoogleChrome/lighthouse pull request #14745
Opened 2023-02-02 00:46 UTC by paulirish

I was looking at report perf and this regex stood out: 

<img width="970" alt="image" src="https://user-images.githubusercontent.com/39191/216202859-b2dc6d27-f9e4-4deb-a006-fcc809dc509f.png">

We already ran into this in #13785 (and fixed by https://github.com/GoogleChrome/lighthouse/pull/13791)

But.. theverge has a non-datauri URL that's 10kb long. and this nasty regex (my fault apparently) really doesn't enjoy working through such a big string.

2023-02-02 01:06 UTC, adamraine approved these changes

2023-02-02 01:14 UTC, connorjclark requested changes
can you add some tests for very long urls?

2023-02-02 01:15 UTC, connorjclark commented on shared/util.js
> +      name = name.slice(0, 200);
perhaps this just works if you swap L214-223 to be first?

2023-04-25 19:09 UTC, connorjclark approved these changes

2023-04-25 19:10 UTC, merged