new_audit: ensure clickjacking mitigation through xfo or csp
GoogleChrome/lighthouse pull request #16290
Opened 2024-12-18 13:43 UTC by sebastian9er

**Summary**
Adding a new audit to Ligththouse, which detects missing Clickjacking mitigation through the X-Frame-Options or Content-Security-Policy HTTP header.

Part of a larger change to introduce more similar header deployments.

Similar to the HSTS audit (https://github.com/GoogleChrome/lighthouse/pull/16257), the description contains a placeholder doc link until the internal doc is approved. @adamraine FYI

2024-12-20 19:37 UTC, adamraine reviewed
Can you revert your changes to `cli/test/smokehouse/frontends/smokehouse-bin.js`

2024-12-20 19:37 UTC, adamraine commented on core/audits/clickjacking-mitigation.js
> +  description: 'Deployment of either the X-Frame-Options or Content-Security-Policy (with the frame-ancestors directive) header will prevent Clickjacking attacks. While the XFO header is simpler to d
```suggestion
  description: 'The `X-Frame-Options` (XFO) header or the `frame-ancestors` directive in the `Content-Security-Policy` (CSP) header can be used to mitigate clickjacking attacks. While the XFO header is simpler to deploy, the `frame-ancestors` CSP directive is more flexible. [Learn more about mitigating clickjacking](https://developer.chrome.com/docs/lighthouse/best-practices/clickjacking-mitigation).',
```

Also what makes the XFO simpler to deploy? Seems like they have the same level of complexity to deploy (just modify header values).

2024-12-20 19:37 UTC, adamraine commented on core/audits/clickjacking-mitigation.js
> +  noClickjackingMitigation: 'No Clickjacking mitigation found.',
```suggestion
  noClickjackingMitigation: 'No XFO or CSP frame-ancestors found',
```

2024-12-20 19:37 UTC, adamraine commented on core/audits/clickjacking-mitigation.js
> +    }
```suggestion
```

This is redundant, if the header lists are empty we will just skip to the bottom anyway.

2024-12-20 19:37 UTC, adamraine commented on core/audits/clickjacking-mitigation.js
> +    }
```suggestion
    // Check for frame-ancestors in CSP.
    for (const cspHeader of cspHeaders) {
      if (cspHeader.includes('frame-ancestors')) {
        // Pass the audit if frame-ancestors is present.
        return {score: 1, results: []};
      }
    }
```

2025-01-09 14:26 UTC, sebastian9er commented on core/audits/clickjacking-mitigation.js
> +  description: 'Deployment of either the X-Frame-Options or Content-Security-Policy (with the frame-ancestors directive) header will prevent Clickjacking attacks. While the XFO header is simpler to d
XFO offers just SAMEORIGIN and DENY, without any granularity and in the past it was easier to deploy (less compatibility concerns), given more browser support than CSP (nowadays, CSP is supported by all major browsers, so maybe "deployment" isn't the correct wording). That being said, for pure clickjacking mitigation, it makes sense to use XFO and only use CSP if more flexibility is needed (CSP should be primarily used for XSS mitigation and mixing it up might confuse some folks).

2025-01-09 18:57 UTC, adamraine requested changes
There are still changes to smokehouse-bin.js, not sure why but can you revert them?

2025-01-09 19:28 UTC, adamraine commented on core/audits/clickjacking-mitigation.js
> +      {key: 'directive', valueType: 'code', subItemsHeading: {key: 'directive'}, label: str_(UIStrings.columnDirective)},
This directive column will never have any value, I think we can just remove it.

2025-01-10 09:18 UTC, sebastian9er commented on core/audits/clickjacking-mitigation.js
> +      {key: 'directive', valueType: 'code', subItemsHeading: {key: 'directive'}, label: str_(UIStrings.columnDirective)},
Removed the column and pushed a new CL.

For the smokehouse-bin, I modified it (timestamp) and pushed the original version afterwards, but it seems to be empty in the PR.

In my branch it's correctly present: https://github.com/sebastian9er/lighthouse/blob/lighthouse-clickjacking/cli/test/smokehouse/frontends/smokehouse-bin.js

2025-01-10 16:20 UTC, adamraine approved these changes

2025-01-10 16:21 UTC, adamraine commented on core/audits/clickjacking-mitigation.js
> +      {key: 'directive', valueType: 'code', subItemsHeading: {key: 'directive'}, label: str_(UIStrings.columnDirective)},
Not sure what's going on, but I think I fixed it

2025-01-10 16:38 UTC, sebastian9er commented on core/audits/clickjacking-mitigation.js
> +      {key: 'directive', valueType: 'code', subItemsHeading: {key: 'directive'}, label: str_(UIStrings.columnDirective)},
Me neither, but thanks :D

2025-01-10 17:03 UTC, sebastian9er commented
Thanks for your help, Adam! Should work now.

2025-01-14 21:12 UTC, adamraine commented
> Are any of the errors related to this audit?

Some of them yes, but it was just some minor audit count / snapshot stuff.

2025-01-22 22:02 UTC, merged